apiVersion: v1
kind: Service
metadata:
  labels:
    app: beerhouse
  name: beerhouse-svc
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 8000
    name: http
  selector:
    app: beerhouse
  type: LoadBalancer